### ISSUE TITLE
Wrong username or password (cmore.fi)

### ISSUE THREAD

**Issue by Dis90** [emilsvennesson/kodi-cmore#1]
Hi,
Just found this addon from your github page and for some reason addon keeps saying that username or password is wrong although I have checked many times that they are right.
Please note that I've edited my credentials in debug log.

Ubuntu: 14.04
Kodi-agile: 7b51a77
Inputstream: f8106f6
Country: Finland

Debug log:
https://paste.ubuntu.com/24524507/

**Comment by emilsvennesson** [comment]
Hi!

I did some testing, and unfortunately it turns out that the Finnish C More site does not utilize the same API as the rest of the Nordic countries. I am going to have to drop cmore.fi for now, but let's hope they merge over to this API in the future.

Sorry. :/

**Comment by Dis90** [comment]
Okay :( I don't think they will ever change same API but lets hope I'm wrong.

Thank you anyway.
