### ISSUE TITLE
Soundstream settings

### ISSUE THREAD

**Issue by CsTpro** [emilsvennesson/kodi-cmore#12]
Sound settings return to sound stream 1/4 dan even if saved as swe 4/4, 

Addon is set on cmore.se

**Comment by emilsvennesson** [comment]
Hi!

This is more a Kodi issue rather than an add-on issue. Have you set your preferred audio language to Swedish in the Kodi settings -> Player -> Language -> Preferred audio language?

**Comment by CsTpro** [comment]
That worked. Tack

**Comment by emilsvennesson** [comment]
Great! :-)
