### ISSUE TITLE
Streams don't start

### ISSUE THREAD

**Issue by atterdal** [emilsvennesson/kodi-cmore#14]
Hi,

I've tried a bunch of different (DRM i guess) tv series and live streams. None of them starts. I've installed the dependencies and the DRM thing from the Google thing it asked for.

TV shows (like swedens master chef) works though.

**Comment by atterdal** [comment]
It works after i removed and manually installed libwidevinecdm.so

**Comment by emilsvennesson** [comment]
Hi! Nice to see that you got it working. This is due to https://github.com/emilsvennesson/script.module.inputstreamhelper/issues/8.
