### ISSUE TITLE
Switch to bbSearchAPI

### ISSUE THREAD

**Issue by jsageryd** [emilsvennesson/kodi-cmore#17]
Hi Emil. I am one of the developers currently working on C More's search service. I thought I'd let you know that the search service (exposed in the `/configuration` endpoint of the mobile BFF as `data.links.bbSearchAPI`) will soon require the query param called `client` to be set. While we don't have any official support for your client (and therefore can make no promises when it comes to changes in our APIs that may break things), I'd recommend you start setting this to avoid the client breaking in the future. If you set it to `cmore-kodi` it would be congruent with what our other clients use. We use the value of this param to monitor which clients are using our service and how they behave.

**Comment by emilsvennesson** [comment]
Hi Johan! First of all, thanks a lot for letting me know about this beforehand. It's much appreciated.

Would you recommend me setting `self.client` (in cmore.py) to `cmore-kodi` or just for the search service request? I'm currently using `cmore-android` because I was unsure if anything else would have been an accepted client.

**Comment by jsageryd** [comment]
Most if not all services allow any value for the `client` param. We don't use this value to restrict usage (for that we use API keys or other means), but we often set this as a required param for the sake of our monitoring. If you should find a service that does not accept the value `cmore-kodi`, reach out and we'll try to get that sorted in one way or another. We'd much rather have each client (supported or not) use a correct identifier rather than scratching our heads about why a client that shouldn't be making requests oddly shows up on our graphs.

**Comment by emilsvennesson** [comment]
I've tried with `cmore-kodi` and it works fine for all services that's currently being used by this addon. :-)

I have some refactoring to do before I can switch to the new search API. I'll see if I can find some time to work on it this weekend.

**Comment by emilsvennesson** [comment]
@jsageryd Are you planning on replacing the search API used by the mobile apps? I just realized that the output from `data.links.bbSearchAPI` is quite different and would need some rework to adapt to.

**Comment by jsageryd** [comment]
The API linked to by `data.links.bbSearchAPI` will likely remain more or less the same for some time to come, save minor updates as we go along. It's hard to make any promises about how long "some time" is, but it won't be tomorrow.

**Comment by emilsvennesson** [comment]
This has now been done.

The end result is a bit of a Frankenstein hybrid between the mobile and web client, but I am pretty satisfied with how it turned out.
