### ISSUE TITLE
libwidevine

### ISSUE THREAD

**Issue by DewGew** [emilsvennesson/kodi-cmore#2]
I can´t get this addon to work on my libreelect krypton. Is libwidevine intalled separately?

**Comment by DewGew** [comment]
I fixed it myself. Installed libwidevine. 
Another thing, c more star has no sound.

**Comment by emilsvennesson** [comment]
Hi! Nice to see that you got it running.

I wouldn't really recommend running this addon on Krypton. There are many issues (sound problems, no subtitles, broken live streams) that's been fixed in inputstream.adaptive for Kodi 18.

**Comment by emilsvennesson** [comment]
Closing as the issue has been resolved.
