### ISSUE TITLE
not playing videos

### ISSUE THREAD

**Issue by tommyhome** [emilsvennesson/kodi-cmore#28]
Hi,
There's a problem playing videos, I can login and browse, but not play.
[kodi.log](https://github.com/emilsvennesson/kodi-cmore/files/2356770/kodi.log)

**Comment by ostgardh** [comment]
Same for me..

Have Cmore change something?

**Comment by Leatherface75** [comment]
Try logout and update login details again.

**Comment by tommyhome** [comment]
That made no difference Leatherface75.

the latest commit seems to have made it work again.
