### ISSUE TITLE
InputStream could not open mpdURL

### ISSUE THREAD

**Issue by phinxy** [emilsvennesson/kodi-cmore#3]
On Win7 x64 & Raspberry pi3 OSMC with all three dependencies installed the live channels will not play. On-demand videos plays fine.

Both Win7 and Rpi3 have the same error message in kodi.log.

Kodi 17 (needs 18?)
Python requests is Version: 2.4.3 (!) I will try to update this. Edit: 2.18 installed. same issue.

` 18 14:00:10.338 T:1958817792  NOTICE: VideoPlayer: Opening: https://level3-usp-dash-live2.cmore.se/live/2219156.isml/2219156.mpd
 17 14:00:10.338 T:1958817792 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
 16 14:00:10.339 T:1449128944  NOTICE: Creating InputStream
 15 14:00:10.725 T:1449128944   ERROR: AddOnLog: InputStream Adaptive: Could not open / parse mpdURL (https://level3-usp-dash-live2.cmore.se/live/2219156.isml/2219156.mpd)
 14 14:00:10.725 T:1449128944   ERROR: CVideoPlayer::OpenInputStream - error opening [https://level3-usp-dash-live2.cmore.se/live/2219156.isml/2219156.mpd]
 13 14:00:10.725 T:1449128944  NOTICE: CVideoPlayer::OnExit()
 12 14:00:10.726 T:1958817792   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.cmore/?action=play&video_id=3355876]
 11 14:00:10.739 T:1958817792  NOTICE: CVideoPlayer::CloseFile()
`

**Comment by emilsvennesson** [comment]
Hi! Yes, Kodi 17.x ships with an out-of-date version of inputstream.adaptive that doesn't work with the C More live streams. Wait for 17.4 or use the nightly builds.
