### ISSUE TITLE
Items not playing.

### ISSUE THREAD

**Issue by Berringer** [emilsvennesson/kodi-cmore#5]
Hey.
I installed this one last night and tried it out.
Nothing is playing though.
There's the "loading" animation and then nothing happens.
Are there any known issues and fixes for this?
Am I missing any deps?

The following is from the log file:

> 12:19:24.743 T:6012   ERROR: Previous line repeats 6 times.
12:19:24.743 T:6012  NOTICE: VideoPlayer: Opening: https://level3-usp-dash.cmore.se/catchup/ISMROOT/CFILM/2017-09-07/STEVEJOBS(3925954_ISM).ism/STEVEJOBS(3925954_ISM).mpd
12:19:24.744 T:6012 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
12:19:24.769 T:6012   ERROR: DXVA::CProcessorHD::IsFormatSupported: Unsupported format 105 for 1.
12:19:24.769 T:13108  NOTICE: Creating InputStream
12:19:24.901 T:13108   ERROR: AddOnLog: InputStream Adaptive: Could not open / parse mpdURL (https://level3-usp-dash.cmore.se/catchup/ISMROOT/CFILM/2017-09-07/STEVEJOBS(3925954_ISM).ism/STEVEJOBS(3925954_ISM).mpd)
12:19:24.901 T:13108   ERROR: CVideoPlayer::OpenInputStream - error opening [https://level3-usp-dash.cmore.se/catchup/ISMROOT/CFILM/2017-09-07/STEVEJOBS(3925954_ISM).ism/STEVEJOBS(3925954_ISM).mpd]
12:19:24.901 T:13108  NOTICE: CVideoPlayer::OnExit()
12:19:24.902 T:6012   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.cmore/?action=play&video_id=3925954]
12:19:24.903 T:6012  NOTICE: CVideoPlayer::CloseFile()

Using 17.4

Edit:
I can play some things now, but I can't play the stuff I am paying Cmore for (Movies, live sports etc), through KODI that is. I have entered my creds correctly.

Edit2: I got it to work with the latest nightly build (v18 2017-Sep-18 04:02), but it's way too unstable.
Got the winevinecdm.dll but still not working on 17.4.
What am I missing? And where do I get it?

**Comment by emilsvennesson** [comment]
Hi! Please post a full, non cut-off debug log.

**Comment by Berringer** [comment]
The log can be found here:
http://paste.ubuntu.com/25564316/

**Comment by emilsvennesson** [comment]
@Berringer It doesn't look like you have enabled debug logging in Kodi. http://kodi.wiki/view/Log_file/Advanced#GUI_settings

**Comment by Berringer** [comment]
@emilsvennesson ah, sorry.
Here is a new log: http://paste.ubuntu.com/25632473/

**Comment by emilsvennesson** [comment]
My guess is that you're using a 64-bit version of the Widevine CDM. Download https://dl.google.com/widevine-cdm/1.4.8.1008-win-ia32.zip and unzip widevinecdm.dll to %APPDATA%\Kodi\cdm.

Make sure to read LICENSE.txt as well so you know what you're getting yourself into.

**Comment by Berringer** [comment]
@emilsvennesson Yes, thank you, that sorted it, now it works!
Great job with this, keep it up!
And I did read the LICENSE.txt, thanks for pointing that out aswell!
