### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by rytmisk** [emilsvennesson/kodi-cmore#8]
Hi
I have now been trying for an hour or so to install this on my firetv running the latest stable Kodi. I get an inputstream.adaptive error so I assume that I need a newer version for Android, but I am unable to find any... I even tried installing on the latest beta of 18 at my ubuntu computer, but the same error came up there. Do you have any tips?
All the best!
Ketil

**Comment by emilsvennesson** [comment]
Hi! Could you try with the latest master and see if you're still having problems? Make sure to install the new script.module.inputstreamhelper dependency.

Sorry for the late response.

**Comment by rytmisk** [comment]
Thanks! Now it works - except my KODI 18 git crashed. But on the firestick it runs flawlessly.
Great work! 
(BTW: Any chance of a tv4play app? - for those who don't pay)

**Comment by emilsvennesson** [comment]
@rytmisk Great! Could you post a debug log from your Kodi 18 install? I'm running Kodi 18 on Linux as well without issues so it shouldn't be a problem to get it up and running. :-)

I kind of have my hands full already so no plans for TV4 Play. I thought Retrospect took care of that?

**Comment by rytmisk** [comment]
Hej igen
It worked now after the daily update so it must have been a temporary error. 
As you probably know, Retrospect has stopped working (sort of at least - he no longer maintains a repo and only fixes broken stuff - doesn't add features) And since tv4play nowadays needs you to log in to access anything besides the news, retro is of no use for that anymore. Thanks!
