### ISSUE TITLE
Text

### ISSUE THREAD

**Issue by rikardfries** [emilsvennesson/kodi-cmore#9]
The addon works well.
The thing that I see as a problem is that I miss text on the film channels.
Do not know if it is doable but it would definitely make me use it more.
Or have I missed something that I should have known..?

**Comment by emilsvennesson** [comment]
Hi! Unfortunately, subtitles are not working on Krypton but have been fixed for Kodi 18.

Sorry for the late response.

**Comment by rikardfries** [comment]
Perfect Thank you, then I know.
Will update to 18 as soon as there is a rc.
